
  <h2>TÉRMINOS Y CONDICIONES DE USO</h2>

  <p>Estos términos y condiciones rigen su acceso y uso del sitio web “www.wolalow.com. Al acceder o utilizar al Sitio Web, está aceptando estas dichas condiciones. Por favor, lea las cuidadosamente los términos y condiciones del sitio web. Si no acepta la totalidad de las mencionadas condiciones, por favor no utilice el Sitio. Le recomendamos volver a esta página periódicamente para revisar las últimas versiones de los términos y condiciones de WolaloW. El acceso o uso continuo del sitio web implica la aceptación de las condiciones y términos actualizados y vigentes.</p>

  <h4>General</h4>

  <p>Este sitio web se provee exclusivamente para facilitar la búsqueda de aquellos personas o instituciones que acceda o utilice el sitio web en busca de contratar un servicio de cadetería o fletes “Clientes” y para facilitar la promoción de aquellos usuarios que buscan ofrecer dichos servicios “Usuarios”. El término “Usuario” hace referencia a los quien ofrece el servicio, tanto como cadete, fletes o ambos. Mientras que el término “Cliente” hace únicamente referencia a las personas que buscan el servicio y no lo ofrecen. </p>
  <p>Tanto los Usuarios como los Clientes registrados en WolaloW serán considerados usuarios del Sitio Web, y deberán de cumplir con las condiciones del mismo.</p>

  <h4>Política de contenido</h4>

  <p>Definiciones: “Contenido” se refiere a texto, imágenes, fotos, direcciones y otras formas de datos o comunicaciones. “Su contenido” se refiere al Contenido que envíe, transmita o haga disponible desde su cuenta de usuario en el Sitio Web como valoraciones, puntuaciones, comentarios, descripciones e información que muestres de forma pública o en tu cuenta de usuario. “Contenido del usuario” se refiere al Contenido que los usuarios envíen, transmitan o hagan disponible desde su cuenta en el Sitio Web.</p>

  <ol>
    <li>Usted entiende que el Sitio Web no controla y no es responsable del Contenido del usuario presente en el Sitio Web, y que al utilizar el sitio usted puede estar expuesto a Contenido del usuario ofensivo, indecente, impreciso, tramposo o bien objetable por algún otro motivo. El Usuario conviene en que puede no confiar en dicho Contenido del usuario y en que ninguna circunstancia WolaloW será responsable por el Contenido del usuario o bien las pérdidas o los daños y perjuicios que el Usuario pueda sufrir como resultado del uso del Contenido del usuario publicado en el Sitio Web u otros medios. El Usuario reconoce que WolaloW no hace un análisis previo ni aprueba Contenido del usuario alguno, no obstante lo cual, WolaloW conservará el derecho (pero no la obligación) a su entera discreción para rechazar, eliminar o quitar aquel Contenido del usuario que se haya puesto a disposición de los demás en el Sitio Web y que implique una violación a la concepción del sitio o las Condiciones o por cualquier otro motivo. </li>
    <li>2.	Usted será único responsable por todo contenido publicado, transmitido, o vinculado desde el Sitio Web y de las consecuencias de su publicación o de haberlo publicado. Con respecto al Contenido publicado, transmitido, o vinculado desde el Sitio Web por usted, usted afirma, representa y/o garantiza que usted tiene todos los derechos de propiedad sobre su Contenido. Sin embargo, al enviar, transmitir o hacer disponible el Contenido en el Sitio Web, usted le otorga a WolaloW una licencia, global, libre de regalías, no exclusiva, sublicensiable y transferible para usar, reproducir, distribuir, preparar trabajos derivados de, exhibir y exponer, en todos los casos con cualquier finalidad, formato, y dispositivo conocido o por conocerse, el Contenido en conexión con el Sitio Web, incluyendo la promoción y distribución de parte o todo el Sitio Web en cualquier formato mediático y a través de cualquier canal mediático. Usted también otorga a cada usuario del Sitio Web una licencia no exclusiva para acceder a su Contenido a través de nuestro sitio. La licencia que usted otorga expira una vez que usted remueve o borra el Contenido del sitio. </li>
  </ol>

  <h4>Política de privacidad</h4>

  <p>Mediante el uso del Sitio Web, el Usuario reconoce y conviene en que WolaloW puede a su sola discreción conservar por tiempo indeterminado o divulgar su Contenido, así como también su información, ya sea direcciones de email, direcciones IP, datos de tiempo y hora, y demás información del Usuario, sobre sus actividades o acceso y uso del sitio, siempre que considere que es necesario por ley o creyendo de buena fe que dicha conservación o divulgación es razonablemente necesaria para lo siguiente: cumplir con un proceso legal; exigir el cumplimiento de estas Condiciones; responder a reclamos sobre la violación de los derechos de terceros en virtud del Contenido; responder reclamos de que información de contacto  de un tercero fue anunciada o transmitida sin su consentimiento o como una forma de acoso; proteger los derechos, la propiedad, o la seguridad personal de WolaloW, sus usuarios o del público en general. </p>

  <h4>Restricciones</h4>

  <p>El Usuario acepta no anunciar, enviar por email ni de cualquier otra forma poner a disposición contenido que: </p>
  <ul>
    <li>Sea contrario a la ley, viole una patente, marca registrada, secreto comercial, derecho de autor u otro derecho de propiedad de cualquier persona, o Contenido respecto del cual el Usuario no tiene derecho a poner a disposición del público conforme a una disposición legal, una relación contractual o fiduciaria. </li>
    <li>Sea dañino, ilícito, amenazador, abusivo, acosador, difamatorio, contenidos para adultos, prostitución, pornográfico, pedofilia, relacionado con juegos de azar, difamatorio, que invada la privacidad de otros o que dañe a menores de cualquier forma; </li>
    <li>Acose, degrade, intimide o sea odioso respecto a un individuo o un grupo de individuos por su religión, género, orientación sexual, raza, etnia, edad o discapacidad; </li>
    <li>Sea falso, engañoso, de una falsa apariencia, tramposo, engañe respecto de la información o que constituya una forma de "atracción y luego se modifique lo ofrecido"; </li>
    <li>Constituya o contiene "marketing afiliado", un "código de referencia a enlace", "mail basura", "spam", "cadenas de cartas", "esquemas de pirámides" o publicidad comercial no solicitada. </li>
    <li>Contiene virus de software u otros códigos, archivos o programas de computación diseñados para interrumpir, destruir o limitar la funcionalidad de un software o de un hardware de computación o de un equipo de telecomunicaciones; </li>
    <li>No "acechar" o de otra forma acosar a otros; </li>
    <li>No recolectar datos personales sobre otros usuarios con fines comerciales o contrarios a la ley; </li>
  </ul>

  <p>Sumado a ello, el Usuario afirma que: </p>

  <ul>
    <li>O es mayor de 18 años, o un menor emancipado o que posee permiso legal de sus padres y/o tutor y que esta completamente habilitado y competente para entrar en estos términos, condiciones, obligaciones, afirmaciones, representaciones, y garantías establecidas en las Condiciones y para respetar y cumplir con estas Condiciones. </li>
  </ul>

  <h4>Responsabilidad</h4>

  <p>Usted acepta que nosotros no somos responsables de lo que otros usuarios publican o hacen en nuestra plataforma.</p>
  <p>Son los Clientes los responsables de seleccionar el Usuario que ofrezca el servicio adecuado a sus necesidades. Al momento de contactar a uno de los Usuarios es responsabilidad de los Clientes cerciorarse de que la información provista por los Usuarios es fehaciente.</p>
  <p>No revisamos ni verificamos el Contenido del Usuario presente en el Sitio Web y no nos involucramos en las transacciones que son celebradas entre los diferentes usuarios. No podemos garantizar ni ofrecer garantía alguna en cuanto a la precisión y contenido de las publicaciones o comunicaciones de los usuarios o de la calidad, seguridad o legalidad de lo que es ofrecido, o con respecto a la capacidad jurídica de la que gozan los usuarios para iniciar o concluir cualquier transacción.</p>
  <p>El usuario reconoce que el Sitio Web puede poner límites respecto al uso del Servicio, con inclusión, entre otras cosas, de la cantidad máxima de días que el Contenido será retenido por el Servicio, la cantidad y el tamaño máximo de los anuncios, los mensajes de email, o de todo otro Contenido que se puede transmitir o almacenar a través del Servicio, y la frecuencia con la cual el Usuario puede acceder al Servicio. El Usuario conviene en que el Sitio Web no es responsable de la eliminación o el fracaso en el almacenamiento de aquel Contenido que se conserva o que se transmite a través del Servicio. El Usuario entiende que el Sitio Web se reserva el derecho para, en todo momento, modificar o interrumpir el Servicio (o una parte de este) con o sin notificación, y que el Sitio Web no será responsable ante el Usuario ni ante un tercero por la modificación, la suspensión o la interrupción del Servicio. El Usuario conviene en que el Sitio Web, a su entera y sola discreción, tiene el derecho (pero no la obligación) de eliminar o desactivar la cuenta del Usuario, de bloquear su dirección de email o IP, o bien de cualquier otra forma cancelar el acceso o el uso del Servicio (o parte de este) por parte del Usuario, en forma inmediata y sin notificación previa. Asimismo, el Sitio Web podrá quitar o descartar Contenido dentro el Servicio, por cualquier motivo, con inclusión, no restrictiva, del momento en que el Sitio Web considere que el Usuario actuó en forma contraria a la letra o el espíritu de las Condiciones. Sumado a ello, el Usuario conviene en que el Sitio Web no será responsable ante el Usuario mismo ni ante un tercero por la cancelación del acceso del Usuario al Servicio. Además, el Usuario conviene en no intentar usar el Servicio luego de la cancelación por parte de el Sitio Web. </p>
  <p>En ningún caso aceptamos responsabilidad de ninguna clase respecto de la publicación de cualquier contenido o material ilegal, amenazador, abusivo, difamatorio, obsceno, pornográfico o indecente o por material de cualquier tipo, incluyendo cualquier información o material que viole o infrinja los derechos de cualquier otra persona o que constituya o fomente conductas que puedan constituir un delito o causen discriminación, den lugar a responsabilidad civil o violen cualquier ley aplicable. Tampoco podemos garantizar un acceso continuo, libre de fallas o seguro a nuestros servicios o garantizar que los defectos en el servicio serán corregidos. No podemos garantizar la continuidad o no interrupción del servicio y no ofrecemos ninguna garantía (ya sea expresa o implícita) en cuanto a la disponibilidad del Sitio Web.</p>
  <p>En consecuencia, hasta donde resulte permitido por la legislación aplicable, renunciamos expresamente a cualquier ofrecimiento de garantías, expresas o implícitas; lo anterior, incluyendo las de calidad, comerciabilidad, calidad comercial, durabilidad, idoneidad para un propósito en particular, garantía de que el contenido es de nuestra propiedad y que no violará derechos de terceros, garantía de título legítimo, garantía de uso pacífico y cualquier otra que derive de la ley. No seremos responsables de ninguna pérdida, ya sea de dinero (incluyendo beneficios o ganancias esperadas), buena voluntad o reputación, o cualquier daño directo o indirecto o de algún perjuicio que pudiera derivarse del uso que usted haga del Sitio Web; lo anterior, incluso en casos en los que usted nos hubiera informado respecto del posible daño o que nosotros, razonablemente, hubiéramos podido prever la posibilidad de que tales daños y perjuicios se produjeran. Algunas jurisdicciones no permiten renunciar al ofrecimiento de garantías o establecer cláusulas de exclusión de responsabilidad por daños; por lo tanto, las limitaciones y exclusiones aquí referidas sólo se aplicarán en la medida permitida por la ley. </p>
